version: '3.9'
services:
  backend:
    container_name: server
    build: .
    ports:
      - 3001:3001
    volumes:
      - ./data:/server/data
    depends_on:
      - db
  db:
    image: mysql:8.0.21
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'