on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2
      
      - name: Instala o node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Executando testes
        run: npm install && npm test