on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2
      
      - name: Instala o node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Instala o Railway CLI
        run: npm install -g railway
      
      - name: Executando testes
        run: npm install && npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2

      - name: Install Railway CLI
        uses: betrybe/setup-railway-cli-action@latest
        with:
          npm-mode: true

      - name: Instala o Railway CLI
        run: npm install -g railway

      - name: Deploy no Raiway
        run: railway up --detach -s backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN}}